export const TypeDevice = {
    LOAD_FIRM: 'LOAD_DEVICE',
    SAVE_FIRM: 'SAVE_DEVICE',
    SET_IS_SAVING_FIRM: 'SET_IS_SAVING_FIRM',
    SET_IS_LOADING_FIRM: 'SET_IS_LOADING_FIRM',

    LOAD_MODEL: 'LOAD_MODEL',
    SAVE_MODEL: 'SAVE_MODEL',
    SET_IS_SAVING_MODEL: 'SET_IS_SAVING_MODEL',
    SET_IS_LOADING_MODEL: 'SET_IS_LOADING_MODEL',
}