export const TypeBudgetAccount = {
    LOAD_BUDGET_ACCOUNT: 'LOAD_BUDGET_ACCOUNT',
    SAVE_BUDGET_ACCOUNT: 'SAVE_BUDGET_ACCOUNT',
    SET_IS_SAVING: 'SET_IS_SAVING',
    SET_IS_LOADING: 'SET_IS_LOADING'
}